---  
- name: Check Firewall Traffic Allowance  
  hosts: all
  ansible_checkpoint_domain: Global
  gather_facts: no  
  tasks:  
    - name: Add, Set or Delete Host
        check_point.mgmt.cp_mgmt_host:
          name: My test host
          color: Red
          comments: Ansible Playbook
          ip_address: 192.168.191.1
          auto_publish_session: true
          state: present
