--- 
- name: Manage Check Point Host
  hosts: all
  gather_facts: no
  tasks:
    - name: Add a new host
      check_point.mgmt.cp_mgmt_checkpoint_host:
        name: "MyHost"
        ip_address: "192.168.1.1"
        state: "present"

