---
- name: add-network
  hosts: all
  ansible_checkpoint_domain: Global
  connection: httpapi
  cp_mgmt_network:
    name: New Network 1
    state: present
    subnet: 192.0.2.0
    subnet_mask: 255.255.255.0
