- name: Add a new network object 
  hosts: all 
  tasks: 
    - name: Add a new network 
      checkpoint_host_rule: 
        name: "New Network" 
        ip_address: "172.16.0.0/16" 
        layer: Network 
        state: present 
