---
- name: Get ARP information
  hosts: 10.138.207.110
  gather_facts: false

  tasks:
    - name: show arp
      raw: "show arp"

      register: print_output

    -  debug: var=print_output.stdout_lines
