---
- name: show clock 
  hosts: all    
  gather_facts: false

  tasks: 
    - name: show clock
      ios_command:   
        commands:     
          - show clock
      register: print_output 
    - debug: var=print_output.stdout_lines
